### ISSUE TITLE
Time prediction

### ISSUE THREAD

**Issue by Espresso0org** [Coding-Enthusiast/FinderOuter#39] opened 2021-12-12 11:24 UTC
How much 8 missing characters from middle gonna take to find with corei7 8700 cpu? Just a estimated time

**Comment by Coding-Enthusiast** [comment] 2021-12-12 15:23
If you run example number 7 it will end in a couple of seconds and will give you a good estimate of the speed as `keys per second`. Then you can compute how much time going through 128,063,081,718,016 would take.  
My guess (I don't have corei7 to test) is that it should be roughly 20 days.  

Duplicate of #30

**Comment by Espresso0org** [comment] 2021-12-12 15:36
Sorry sir i made a mistake.its 7 characters not 8.my pc found 5 characters in the middle about 50min.why 7 and 8 gonna take a lot more time

**Comment by Coding-Enthusiast** [comment] 2021-12-13 03:13
> my pc found 5 characters in the middle about 50min.

Are you sure your CPU is corei7 8700? My corei3-6100 takes 20 seconds to find 5 missing characters from middle.

> why 7 and 8 gonna take a lot more time
I used 60 million key/sec which is the slowest speed. Each missing character increases the total number of keys to check by a factor of 58.  
```
1 missing -> 58  
2 missing -> 58 * 58 = 3,364
3 missing -> 58 * 58 * 58 = 195,112
...
5 missing ->         656,356,768
7 missing ->   2,207,984,167,552
8 missing -> 128,063,081,718,016
```

**Comment by Espresso0org** [comment] 2021-12-13 18:15
Its 7 characters next each other.after 1 day its still 0% . My speed is 10m keys/sec

**Closed** 2021-12-17 10:10 UTC
